//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDCONTABILIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTASCONT
    {
        public int ID { get; set; }
        public string DESCRIPCION { get; set; }
        public string PERMITEMOV { get; set; }
        public Nullable<int> TIPO { get; set; }
        public Nullable<int> NIVEL { get; set; }
        public Nullable<int> BALANCE { get; set; }
        public Nullable<int> CUENTA_MAYOR { get; set; }
        public string ESTADO { get; set; }
    }
}
