//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDCONTABILIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTRADACONTABLE
    {
        public int ID_ASIENTO { get; set; }
        public string DESCRIPCION { get; set; }
        public string IDENTIFICADOR_AUX { get; set; }
        public string CUENTA { get; set; }
        public string TIPOMOV { get; set; }
        public Nullable<System.DateTime> FECHAASIENTO { get; set; }
        public Nullable<double> MONTOASIENTO { get; set; }
        public string ESTADO { get; set; }
    }
}
