//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDCONTABILIDAD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CONTABILIDADDBEntities : DbContext
    {
        public CONTABILIDADDBEntities()
            : base("name=CONTABILIDADDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CUENTASCONT> CUENTASCONT { get; set; }
        public virtual DbSet<ENTRADACONTABLE> ENTRADACONTABLE { get; set; }
        public virtual DbSet<SISTEMASAUX> SISTEMASAUX { get; set; }
        public virtual DbSet<TIPOCUENTA> TIPOCUENTA { get; set; }
        public virtual DbSet<TIPOMONEDA> TIPOMONEDA { get; set; }
    }
}
